spring.application.name=serverAmazon

spring.datasource.url=jdbc:mysql://database-1.cpoa60a6ibye.us-east-2.rds.amazonaws.com:3306/serveramazon
spring.datasource.username=admin
spring.datasource.password=Cabj1234.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true